/**
 * @file errno.h
 * @author Kevin Oehme
 * @copyright MIT
 */

#pragma once

#include <stdint.h>

// STANDARD ERRORS (POSIX / LINUX STYLE)
#define EPERM 1		/* OPERATION NOT PERMITTED */
#define ENOENT 2	/* NO SUCH FILE OR DIRECTORY */
#define ESRCH 3		/* NO SUCH PROCESS */
#define EINTR 4		/* INTERRUPTED SYSTEM CALL */
#define EIO 5		/* I/O ERROR */
#define ENXIO 6		/* NO SUCH DEVICE OR ADDRESS */
#define E2BIG 7		/* ARG LIST TOO LONG */
#define ENOEXEC 8	/* EXEC FORMAT ERROR */
#define EBADF 9		/* BAD FILE NUMBER */
#define ECHILD 10	/* NO CHILD PROCESSES */
#define EAGAIN 11	/* TRY AGAIN */
#define ENOMEM 12	/* OUT OF MEMORY */
#define EACCES 13	/* PERMISSION DENIED */
#define EFAULT 14	/* BAD ADDRESS */
#define ENOTBLK 15	/* BLOCK DEVICE REQUIRED */
#define EBUSY 16	/* DEVICE OR RESOURCE BUSY */
#define EEXIST 17	/* FILE EXISTS */
#define EXDEV 18	/* CROSS-DEVICE LINK */
#define ENODEV 19	/* NO SUCH DEVICE */
#define ENOTDIR 20	/* NOT A DIRECTORY */
#define EISDIR 21	/* IS A DIRECTORY */
#define EINVAL 22	/* INVALID ARGUMENT */
#define ENFILE 23	/* FILE TABLE OVERFLOW */
#define EMFILE 24	/* TOO MANY OPEN FILES */
#define ENOTTY 25	/* NOT A TYPEWRITER */
#define ETXTBSY 26	/* TEXT FILE BUSY */
#define EFBIG 27	/* FILE TOO LARGE */
#define ENOSPC 28	/* NO SPACE LEFT ON DEVICE */
#define ESPIPE 29	/* ILLEGAL SEEK */
#define EROFS 30	/* READ-ONLY FILE SYSTEM */
#define EMLINK 31	/* TOO MANY LINKS */
#define EPIPE 32	/* BROKEN PIPE */
#define EDOM 33		/* MATH ARGUMENT OUT OF DOMAIN OF FUNC */
#define ERANGE 34	/* MATH RESULT NOT REPRESENTABLE */
#define EDEADLK 35	/* RESOURCE DEADLOCK WOULD OCCUR */
#define ENAMETOOLONG 36 /* FILE NAME TOO LONG */
#define ENOLCK 37	/* NO RECORD LOCKS AVAILABLE */
#define ENOSYS 38	/* FUNCTION NOT IMPLEMENTED */
#define ENOTEMPTY 39	/* DIRECTORY NOT EMPTY */
#define ELOOP 40	/* TOO MANY SYMBOLIC LINKS ENCOUNTERED */

// SYSV/XENIX/STREAMS ERRORS
#define EWOULDBLOCK 41 /* OPERATION WOULD BLOCK */
#define ENOMSG 42      /* NO MESSAGE OF DESIRED TYPE */
#define EIDRM 43       /* IDENTIFIER REMOVED */
#define ECHRNG 44      /* CHANNEL NUMBER OUT OF RANGE */
#define EL2NSYNC 45    /* LEVEL 2 NOT SYNCHRONIZED */
#define EL3HLT 46      /* LEVEL 3 HALTED */
#define EL3RST 47      /* LEVEL 3 RESET */
#define ELNRNG 48      /* LINK NUMBER OUT OF RANGE */
#define EUNATCH 49     /* PROTOCOL DRIVER NOT ATTACHED */
#define ENOCSI 50      /* NO CSI STRUCTURE AVAILABLE */
#define EL2HLT 51      /* LEVEL 2 HALTED */
#define EBADE 52       /* INVALID EXCHANGE */
#define EBADR 53       /* INVALID REQUEST DESCRIPTOR */
#define EXFULL 54      /* EXCHANGE FULL */
#define ENOANO 55      /* NO ANODE */
#define EBADRQC 56     /* INVALID REQUEST CODE */
#define EBADSLT 57     /* INVALID SLOT */
#define EDEADLOCK 58   /* FILE LOCKING DEADLOCK ERROR */
#define EBFONT 59      /* BAD FONT FILE FORMAT */

// STREAMS
#define ENOSTR 60  /* DEVICE NOT A STREAM */
#define ENODATA 61 /* NO DATA AVAILABLE */
#define ETIME 62   /* TIMER EXPIRED */
#define ENOSR 63   /* OUT OF STREAMS RESOURCES */

// NETWORK
#define ENONET 64    /* MACHINE IS NOT ON THE NETWORK */
#define ENOPKG 65    /* PACKAGE NOT INSTALLED */
#define EREMOTE 66   /* OBJECT IS REMOTE */
#define ENOLINK 67   /* LINK HAS BEEN SEVERED */
#define EADV 68	     /* ADVERTISE ERROR */
#define ESRMNT 69    /* SRMOUNT ERROR */
#define ECOMM 70     /* COMMUNICATION ERROR ON SEND */
#define EPROTO 71    /* PROTOCOL ERROR */
#define EMULTIHOP 72 /* MULTIHOP ATTEMPTED */
#define EDOTDOT 73   /* RFS SPECIFIC ERROR */

// FILE SYSTEMS
#define EBADMSG 74   /* NOT A DATA MESSAGE */
#define EOVERFLOW 75 /* VALUE TOO LARGE FOR DEFINED DATA TYPE */
#define ENOTUNIQ 76  /* NAME NOT UNIQUE ON NETWORK */
#define EBADFD 77    /* FILE DESCRIPTOR IN BAD STATE */
#define EREMCHG 78   /* REMOTE ADDRESS CHANGED */
#define ELIBACC 79   /* CANNOT ACCESS NEEDED SHARED LIBRARY */
#define ELIBBAD 80   /* ACCESSING A CORRUPTED SHARED LIBRARY */
#define ELIBSCN 81   /* .LIB SECTION IN A.OUT CORRUPTED */
#define ELIBMAX 82   /* TOO MANY SHARED LIBRARIES */
#define ELIBEXEC 83  /* CANNOT EXEC A SHARED LIBRARY DIRECTLY */
#define EILSEQ 84    /* ILLEGAL BYTE SEQUENCE */
#define ERESTART 85  /* INTERRUPTED SYSTEM CALL SHOULD BE RESTARTED */
#define ESTRPIPE 86  /* STREAMS PIPE ERROR */

// SOCKETS / NETWORK
#define EUSERS 87	   /* TOO MANY USERS */
#define ENOTSOCK 88	   /* SOCKET OPERATION ON NON-SOCKET */
#define EDESTADDRREQ 89	   /* DESTINATION ADDRESS REQUIRED */
#define EMSGSIZE 90	   /* MESSAGE TOO LONG */
#define EPROTOTYPE 91	   /* PROTOCOL WRONG TYPE FOR SOCKET */
#define ENOPROTOOPT 92	   /* PROTOCOL NOT AVAILABLE */
#define EPROTONOSUPPORT 93 /* PROTOCOL NOT SUPPORTED */
#define ESOCKTNOSUPPORT 94 /* SOCKET TYPE NOT SUPPORTED */
#define EOPNOTSUPP 95	   /* OPERATION NOT SUPPORTED ON TRANSPORT ENDPOINT */
#define EPFNOSUPPORT 96	   /* PROTOCOL FAMILY NOT SUPPORTED */
#define EAFNOSUPPORT 97	   /* ADDRESS FAMILY NOT SUPPORTED BY PROTOCOL */
#define EADDRINUSE 98	   /* ADDRESS ALREADY IN USE */
#define EADDRNOTAVAIL 99   /* CANNOT ASSIGN REQUESTED ADDRESS */
#define ENETDOWN 100	   /* NETWORK IS DOWN */
#define ENETUNREACH 101	   /* NETWORK IS UNREACHABLE */
#define ENETRESET 102	   /* NETWORK DROPPED CONNECTION ON RESET */
#define ECONNABORTED 103   /* SOFTWARE CAUSED CONNECTION ABORT */
#define ECONNRESET 104	   /* CONNECTION RESET BY PEER */
#define ENOBUFS 105	   /* NO BUFFER SPACE AVAILABLE */
#define EISCONN 106	   /* TRANSPORT ENDPOINT ALREADY CONNECTED */
#define ENOTCONN 107	   /* TRANSPORT ENDPOINT NOT CONNECTED */
#define ESHUTDOWN 108	   /* CANNOT SEND AFTER TRANSPORT ENDPOINT SHUTDOWN */
#define ETOOMANYREFS 109   /* TOO MANY REFERENCES: CANNOT SPLICE */
#define ETIMEDOUT 110	   /* CONNECTION TIMED OUT */
#define ECONNREFUSED 111   /* CONNECTION REFUSED */
#define EHOSTDOWN 112	   /* HOST IS DOWN */
#define EHOSTUNREACH 113   /* NO ROUTE TO HOST */
#define EALREADY 114	   /* OPERATION ALREADY IN PROGRESS */
#define EINPROGRESS 115	   /* OPERATION NOW IN PROGRESS */
#define ESTALE 116	   /* STALE NFS FILE HANDLE */
#define EUCLEAN 117	   /* STRUCTURE NEEDS CLEANING */
#define ENOTNAM 118	   /* NOT A XENIX NAMED TYPE FI*/