#ifndef ICARIUS_H
#define ICARIUS_H

#define PAGE_SIZE (1024 * 4 * 1024)

#define USER_CODE_START 0x00000000
#define USER_CODE_SIZE (PAGE_SIZE)
#define USER_CODE_END (USER_CODE_START + USER_CODE_SIZE - 1)

#define USER_BSS_START (USER_CODE_END + 1)
#define USER_BSS_SIZE (PAGE_SIZE)
#define USER_BSS_END (USER_BSS_START + USER_BSS_SIZE - 1)

#define USER_HEAP_START (USER_BSS_END + 1)
#define USER_HEAP_SIZE (PAGE_SIZE)
#define USER_HEAP_END (USER_HEAP_START + USER_HEAP_SIZE - 1)

#define USER_STACK_SIZE (PAGE_SIZE)
#define USER_STACK_START (USER_STACK_END - USER_STACK_SIZE + 1) // 0xBFC00000
#define USER_STACK_END 0xBFFFFFFF

#endif